### ISSUE TITLE
Is the withEnv method/feature available?

### ISSUE THREAD

**Issue by fatiiates** [snowdrop/java-buildpack-client#15]
I've read [comment line](https://github.com/snowdrop/java-buildpack-client/blob/fdc5eaa09fa970f3c626c4f119b53534b370b038/src/main/java/dev/snowdrop/buildpack/BuildpackBuilder.java#L27) and [note](https://github.com/snowdrop/java-buildpack-client/blob/fdc5eaa09fa970f3c626c4f119b53534b370b038/README.md#overview) that it's not implemented in code yet. If I'm not wrong when I review the [codes](https://github.com/snowdrop/java-buildpack-client/blob/main/src/main/java/dev/snowdrop/buildpack/BuildpackBuilderImpl.java#L286), you can transfer variables into the /platform/env directory. Is this feature available now ? Or maybe I can help if there is a feature that needs to be added.

**Comment by cmoulliard** [comment]
Can you please reply @BarDweller to Fatih ?

**Comment by BarDweller** [comment]
The recent update to platform 12 offers the ability to set env vars via the platform.
Closing this one.
