### ISSUE TITLE
Right place to maintain this project ?

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/java-buildpack-client#3]
## Question

What is the best and right place to maintain this project (here, snowdrop github org, ...) ?
@BarDweller

**Comment by BarDweller** [comment]
We should probably move this into snowdrop git org, with the package rename complete, it does kinda feel orphaned from there while it lives here =)

**Comment by cmoulliard** [comment]
> We should probably move this into snowdrop git org

I agree, you should move it.

**Comment by BarDweller** [comment]
Done.
