### ISSUE TITLE
Support Platform API : 0.10

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/java-buildpack-client#58]
## Issue

The current project cannot work with the new UBI Builder image (quay.io/snowdrop/ubi-builder) as it has been developed to support the `Platform API - spec 0.4`

```
        if(!environment.containsKey("CNB_PLATFORM_API")) environment.put("CNB_PLATFORM_API", "0.4");
```

which is incompatible with recent releases of lifecycle

See: https://github.com/snowdrop/java-buildpack-client/actions/runs/7143725404/job/19455839296#step:7:18
```
ERROR: failed to set platform API: platform API version '0.4' is incompatible with the lifecycle
```

**Comment by BarDweller** [comment]
Duplicate of https://github.com/snowdrop/java-buildpack-client/issues/38
